### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by prohtex** [john-stephens/zebra-mac-label-automator#5]
I can't wait to try this out. We've had nothing but misery trying to work with Allensby, with their expensive products, broken and user-hostile licensing system. I've used imagemagick and VIPS to create bitmap images but didn't realize this was the cause for the blurry/dithered CUPS labels.

**Comment by john-stephens** [comment]
Let me know how it works out for you! If it does work for you, I would also appreciate knowing the printer model you are using so that I can add it to the list.
